# Generated by Django 3.2.4 on 2021-06-24 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0056_alter_liveclass_details_end_time'),
        ('MentorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.mentor'),
        ),
    ]
