# Generated by Django 3.2.4 on 2021-06-24 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0057_alter_liveclass_details_end_time'),
        ('MentorApp', '0002_questionmodel_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='conceptual_class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.liveclass_details'),
        ),
    ]
