# Generated by Django 3.2.4 on 2021-06-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorApp', '0002_auto_20210630_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answer',
            field=models.TextField(default=' '),
        ),
    ]
