# Generated by Django 3.2.4 on 2021-06-24 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0059_alter_liveclass_details_end_time'),
        ('MentorApp', '0003_alter_questionmodel_conceptual_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='doubt_class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.doubtclasses'),
        ),
    ]
