# Generated by Django 3.2.4 on 2021-06-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MentorApp', '0004_alter_questionmodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
