# Generated by Django 3.2.4 on 2021-06-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liveclass_api', '0040_alter_liveclass_details_end_time'),
        ('Mentors', '0002_auto_20210622_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('ratings', models.IntegerField(default=0)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mentors',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('doubt_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.liveclass_details')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mentors.mentors')),
            ],
        ),
    ]
