# Generated by Django 3.2.4 on 2021-06-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0049_auto_20210623_1620'),
        ('Mentors', '0006_alter_questionmodel_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.mentor'),
        ),
        migrations.DeleteModel(
            name='Mentors',
        ),
    ]
