# Generated by Django 3.2.4 on 2021-06-23 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mentors', '0007_auto_20210623_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmodel',
            name='mentor',
        ),
    ]
