# Generated by Django 3.2.4 on 2021-06-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField()),
                ('no_of_students_registered', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Class',
            },
        ),
        migrations.CreateModel(
            name='LiveClass_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=30)),
                ('chapter_details', models.TextField()),
                ('class_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'LiveClass_details',
            },
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Mentors',
            },
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobile_number', models.IntegerField()),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.liveclass')),
            ],
            options={
                'verbose_name_plural': 'User_details',
            },
        ),
        migrations.CreateModel(
            name='LiveClass_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.liveclass_details')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.user_details')),
            ],
            options={
                'verbose_name_plural': 'LiveClass_registration',
            },
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='mentor_name',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.mentor'),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.liveclass'),
        ),
    ]
