# Generated by Django 3.1.13 on 2021-07-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtclasses',
            name='group',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doubtclasses',
            name='quizzes',
            field=models.IntegerField(default=0),
        ),
    ]
