# Generated by Django 3.2.4 on 2021-06-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass_details',
            name='doubtsAddressed',
            field=models.IntegerField(default=0),
        ),
    ]
