# Generated by Django 3.1.13 on 2021-07-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0002_auto_20210708_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtclasses',
            name='no_of_students_rated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='no_of_students_rated',
            field=models.IntegerField(default=0),
        ),
    ]
