# Generated by Django 3.2.4 on 2021-06-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0002_alter_user_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass_details',
            name='duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='mentor',
            name='ratings',
            field=models.FloatField(default=2.5),
        ),
    ]
