# Generated by Django 3.2.4 on 2021-06-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0002_liveclass_details_doubtsaddressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtclasses',
            name='isDraft',
            field=models.BooleanField(default=False),
        ),
    ]
