# Generated by Django 3.2.4 on 2021-06-19 04:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0003_auto_20210618_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_registered', models.BooleanField(default=False)),
                ('is_attended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'SavedClasses',
            },
        ),
        migrations.RemoveField(
            model_name='liveclass_details',
            name='duration',
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='doubtsAddressed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 4, 21, 37, 146127, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='isDoubtClass',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LiveClass_registration',
        ),
        migrations.AddField(
            model_name='savedclass',
            name='class_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.liveclass_details'),
        ),
        migrations.AddField(
            model_name='savedclass',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.user_details'),
        ),
    ]
