# Generated by Django 3.2.4 on 2021-06-19 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0004_auto_20210619_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedclass',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 5, 4, 51, 574016, tzinfo=utc)),
        ),
    ]
