# Generated by Django 3.1.13 on 2021-07-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0004_auto_20210710_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtclasses',
            name='meeting_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doubtclasses',
            name='meeting_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='meeting_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='meeting_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
