# Generated by Django 3.1.13 on 2021-07-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0005_auto_20210712_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doubtclasses',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
