# Generated by Django 3.2.4 on 2021-06-19 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0005_auto_20210619_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 6, 33, 36, 606188, tzinfo=utc)),
        ),
    ]
