# Generated by Django 3.2.4 on 2021-06-19 09:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liveclass_api', '0006_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 9, 19, 31, 457703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='savedclass',
            name='class_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.liveclass_details'),
        ),
        migrations.AlterField(
            model_name='savedclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
