# Generated by Django 3.2.4 on 2021-06-19 09:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0007_auto_20210619_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 9, 20, 2, 577323, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='savedclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.user_details'),
        ),
    ]
