# Generated by Django 3.2.4 on 2021-06-19 13:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0009_auto_20210619_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedclass',
            name='is_attended',
        ),
        migrations.RemoveField(
            model_name='savedclass',
            name='is_registered',
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='no_of_students_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='no_of_students_registered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 13, 17, 42, 880546, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='ratings',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
