# Generated by Django 3.2.4 on 2021-06-19 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0011_auto_20210619_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 13, 42, 19, 152264, tzinfo=utc)),
        ),
    ]
