# Generated by Django 3.2.4 on 2021-06-19 15:57

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liveclass_api', '0013_auto_20210619_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 15, 57, 30, 537186, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='registeredclass',
            unique_together={('class_details', 'user')},
        ),
    ]
