# Generated by Django 3.2.4 on 2021-06-21 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0014_auto_20210619_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 4, 29, 26, 229397, tzinfo=utc)),
        ),
    ]
