# Generated by Django 3.2.4 on 2021-06-21 10:47

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liveclass_api', '0015_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 10, 47, 56, 567965, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='savedclass',
            unique_together={('class_details', 'user')},
        ),
    ]
