# Generated by Django 3.2.4 on 2021-06-21 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0016_auto_20210621_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 10, 51, 17, 938156, tzinfo=utc)),
        ),
    ]
