# Generated by Django 3.2.4 on 2021-06-21 11:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0017_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass_details',
            name='isDraft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 11, 48, 38, 424171, tzinfo=utc)),
        ),
    ]
