# Generated by Django 3.2.4 on 2021-06-22 03:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0018_auto_20210621_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_names', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='liveclass_details',
            name='chapter_name',
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 3, 19, 40, 270655, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='chapter_name',
            field=models.ManyToManyField(to='liveclass_api.ChapterNames'),
        ),
    ]
