# Generated by Django 3.2.4 on 2021-06-22 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0019_auto_20210622_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 3, 22, 55, 270464, tzinfo=utc)),
        ),
    ]
