# Generated by Django 3.2.4 on 2021-06-22 03:41

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liveclass_api', '0022_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveclass_details',
            old_name='chapter_details',
            new_name='chapter_ids',
        ),
        migrations.RenameField(
            model_name='liveclass_details',
            old_name='mentor_name',
            new_name='mentor_id',
        ),
        migrations.RenameField(
            model_name='registeredclass',
            old_name='class_details',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='savedclass',
            old_name='class_details',
            new_name='class_id',
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 3, 41, 26, 936022, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='registeredclass',
            unique_together={('class_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='savedclass',
            unique_together={('class_id', 'user')},
        ),
    ]
