# Generated by Django 3.2.4 on 2021-06-22 03:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0023_auto_20210622_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass_details',
            name='chapter_name',
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='chapter_details',
            field=models.TextField(default=''),
        ),
        migrations.RemoveField(
            model_name='liveclass_details',
            name='chapter_ids',
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='chapter_ids',
            field=models.ManyToManyField(to='liveclass_api.ChapterNames'),
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 3, 42, 39, 264849, tzinfo=utc)),
        ),
    ]
