# Generated by Django 3.2.4 on 2021-06-22 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0024_auto_20210622_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 6, 26, 59, 819157, tzinfo=utc)),
        ),
    ]
