# Generated by Django 3.2.4 on 2021-06-22 09:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0025_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubtClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubtClass_details', models.TextField()),
                ('class_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('doubtsAddressed', models.IntegerField(default=0)),
                ('no_of_students_registered', models.IntegerField(default=0)),
                ('no_of_students_attended', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DoubtClasses',
            },
        ),
        migrations.RemoveField(
            model_name='liveclass_details',
            name='doubtsAddressed',
        ),
        migrations.RemoveField(
            model_name='liveclass_details',
            name='isDoubtClass',
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 9, 38, 55, 815916, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='doubtClass',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='liveclass_api.doubtclasses'),
        ),
    ]
