# Generated by Django 3.2.4 on 2021-06-22 09:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0026_auto_20210622_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass_details',
            name='isDoubtClass',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 9, 40, 53, 722295, tzinfo=utc)),
        ),
    ]
