# Generated by Django 3.2.4 on 2021-06-22 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0028_auto_20210622_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveclass_details',
            name='isDoubtClass',
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 9, 44, 45, 51411, tzinfo=utc)),
        ),
    ]
