# Generated by Django 3.2.4 on 2021-06-22 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0029_auto_20210622_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtclasses',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doubtclasses',
            name='mentor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.mentor'),
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 35, 33, 833273, tzinfo=utc)),
        ),
    ]
