# Generated by Django 3.2.4 on 2021-06-22 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0030_auto_20210622_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 37, 45, 18609, tzinfo=utc)),
        ),
    ]
