# Generated by Django 3.2.4 on 2021-06-22 11:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0031_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubtclasses',
            name='mentor_id',
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 11, 57, 28, 555131, tzinfo=utc)),
        ),
    ]
