# Generated by Django 3.2.4 on 2021-06-22 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0032_auto_20210622_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubtclasses',
            name='mentor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.mentor'),
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 12, 56, 57, 120725, tzinfo=utc)),
        ),
    ]
