# Generated by Django 3.2.4 on 2021-06-22 13:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0033_auto_20210622_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubtclasses',
            name='is_draft',
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 13, 3, 41, 801189, tzinfo=utc)),
        ),
    ]
