# Generated by Django 3.2.4 on 2021-06-23 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0034_auto_20210622_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 3, 52, 30, 435434, tzinfo=utc)),
        ),
    ]
