# Generated by Django 3.2.4 on 2021-06-23 05:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0036_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 5, 57, 49, 260236, tzinfo=utc)),
        ),
    ]
