# Generated by Django 3.2.4 on 2021-06-23 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0037_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liveclass_details',
            old_name='class_time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='doubtclasses',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='liveclass_details',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 6, 30, 24, 612187, tzinfo=utc)),
        ),
    ]
