# Generated by Django 3.2.4 on 2021-06-23 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0039_auto_20210623_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 23, 11, 2, 56, 418323, tzinfo=utc)),
        ),
    ]
