# Generated by Django 3.2.4 on 2021-06-24 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0055_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 3, 22, 37, 194261, tzinfo=utc)),
        ),
    ]
