# Generated by Django 3.2.4 on 2021-06-24 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liveclass_api', '0059_alter_liveclass_details_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='RegisteredClassNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceptual_class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.liveclass_details')),
                ('doubtclass_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.doubtclasses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RegisteredClass',
                'unique_together': {('conceptual_class_id', 'user', 'doubtclass_id')},
            },
        ),
    ]
