# Generated by Django 3.2.4 on 2021-06-25 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liveclass_api', '0060_auto_20210625_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDoubtClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubtclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveclass_api.doubtclasses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'RegisteDoubtClass',
                'unique_together': {('doubtclass', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='RegisteredClassNew2',
        ),
    ]
