# Generated by Django 3.2.4 on 2021-06-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0060_auto_20210624_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeredclassnew',
            options={'verbose_name_plural': 'RegisteredClassNew'},
        ),
    ]
