# Generated by Django 3.2.4 on 2021-06-24 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liveclass_api', '0062_alter_registeredclassnew_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registeredclassnew',
            unique_together={('conceptual_class_id', 'user')},
        ),
    ]
