# Generated by Django 3.2.4 on 2021-06-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0063_alter_registeredclassnew_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registeredclassnew',
            old_name='conceptual_class_id',
            new_name='conceptual_class',
        ),
        migrations.RenameField(
            model_name='registeredclassnew',
            old_name='doubtclass_id',
            new_name='doubtclass',
        ),
    ]
