# Generated by Django 3.2.4 on 2021-06-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0064_alter_doubtclasses_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
