# Generated by Django 3.2.4 on 2021-06-28 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('liveclass_api', '0068_auto_20210628_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='user',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='name',
            field=models.OneToOneField(max_length=30, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
