# Generated by Django 3.2.4 on 2021-06-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveclass_api', '0074_registerednames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass_details',
            name='registered_students',
            field=models.ManyToManyField(blank=True, null=True, to='liveclass_api.RegisteredNames'),
        ),
    ]
